import './globals.css'
import type { Metadata } from 'next'
import { Montserrat , Raleway} from 'next/font/google'

const montserrat = Montserrat({subsets : ["latin"]})

export const metadata: Metadata = {
  title: 'E-voting Osis',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>{children}</body>
    </html>
  )
}
